name: diart
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.13
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - cffi=1.17.1
  - ffmpeg=4.3.2
  - freetype=2.12.1
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gmp=6.3.0
  - gnutls=3.6.13
  - lame=3.100
  - ld_impl_linux-64=2.43
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - liblapack=3.9.0
  - liblzma=5.6.3
  - libnsl=2.0.1
  - libogg=1.3.5
  - libopenblas=0.3.28
  - libopus=1.3.1
  - libpng=1.6.46
  - libsndfile=1.2.2
  - libsqlite=3.48.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - mpg123=1.32.9
  - ncurses=6.5
  - nettle=3.6
  - numpy=2.2.2
  - openh264=2.1.1
  - openssl=3.4.0
  - pip=25.0
  - portaudio=19.6.0
  - pycparser=2.22
  - pysoundfile=0.12.1
  - python=3.10.16
  - python_abi=3.10
  - readline=8.2
  - setuptools=75.8.0
  - tk=8.6.13
  - wheel=0.45.1
  - x264=1!161.3030
  - pip:
      - attrs==25.1.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - diart==0.9.1
      - fsspec==2025.2.0
      - idna==3.10
      - intervaltree==3.1.0
      - jinja2==3.1.5
      - markupsafe==3.0.2
      - matplotlib==3.3.3
      - pandas==2.2.3
      - pexpect==4.9.0
      - psutil==6.1.1
      - ptyprocess==0.7.0
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - pyyaml==6.0.2
      - requests==2.32.3
      - rx==3.2.0
      - six==1.17.0
      - sounddevice==0.5.1
      - torchvision==0.21.0
      - tzdata==2025.1
      - urllib3==2.3.0
      - websocket-client==1.8.0
      - websocket-server==0.6.4
