name: Pytest

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install apt dependencies
      run: |
        sudo add-apt-repository ppa:savoury1/ffmpeg4
        sudo apt-get update
        sudo apt-get -y install ffmpeg libportaudio2=19.6.0-1.1

    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[tests]

    - name: Run tests
      run: |
        pytest
